### ISSUE TITLE
New GUI

### ISSUE THREAD

**Issue by Motzkiste** [Motzkiste/Ampi-lution#43]
### Current: [0.25.0](https://github.com/As-hina-Gaming/Ampi-lution/milestone/2)
- [x] As-hina-Gaming/Ampi-lution#24

### Next up: [0.25.1](https://github.com/As-hina-Gaming/Ampi-lution/milestone/3)
- [ ] As-hina-Gaming/Ampi-lution-Resources#2
- [ ] As-hina-Gaming/Ampi-lution-Resources#3
- [ ] As-hina-Gaming/Ampi-lution-Resources#4

### TBA
- [ ] As-hina-Gaming/Ampi-lution-Resources#5
- [ ] As-hina-Gaming/Ampi-lution-Resources#6
- [ ] As-hina-Gaming/Ampi-lution-Resources#7
- [ ] As-hina-Gaming/Ampi-lution-Resources#8
- [ ] As-hina-Gaming/Ampi-lution-Resources#9
- [ ] As-hina-Gaming/Ampi-lution-Resources#10
- [ ] As-hina-Gaming/Ampi-lution-Resources#11
- [ ] As-hina-Gaming/Ampi-lution-Resources#12
- [ ] As-hina-Gaming/Ampi-lution-Resources#13
- [ ] As-hina-Gaming/Ampi-lution-Resources#14
- [ ] As-hina-Gaming/Ampi-lution-Resources#15
- [ ] As-hina-Gaming/Ampi-lution-Resources#16
- [ ] As-hina-Gaming/Ampi-lution-Resources#17
- [ ] As-hina-Gaming/Ampi-lution-Resources#18
- [ ] As-hina-Gaming/Ampi-lution-Resources#19
- [ ] As-hina-Gaming/Ampi-lution-Resources#20
- [ ] As-hina-Gaming/Ampi-lution-Resources#21
- [ ] As-hina-Gaming/Ampi-lution-Resources#22
- [ ] As-hina-Gaming/Ampi-lution-Resources#23
- [ ] As-hina-Gaming/Ampi-lution-Resources#24
- [ ] As-hina-Gaming/Ampi-lution-Resources#25
- [ ] As-hina-Gaming/Ampi-lution-Resources#26
- [ ] As-hina-Gaming/Ampi-lution-Resources#27
- [ ] As-hina-Gaming/Ampi-lution-Resources#28
- [ ] As-hina-Gaming/Ampi-lution-Resources#29
- [ ] As-hina-Gaming/Ampi-lution-Resources#30
- [ ] As-hina-Gaming/Ampi-lution-Resources#31
- [ ] As-hina-Gaming/Ampi-lution-Resources#32
- [ ] As-hina-Gaming/Ampi-lution-Resources#33
- [ ] As-hina-Gaming/Ampi-lution-Resources#34
- [ ] As-hina-Gaming/Ampi-lution-Resources#35
- [ ] As-hina-Gaming/Ampi-lution-Resources#36
- [ ] As-hina-Gaming/Ampi-lution-Resources#37
- [ ] As-hina-Gaming/Ampi-lution-Resources#38
- [ ] As-hina-Gaming/Ampi-lution-Resources#39
- [ ] As-hina-Gaming/Ampi-lution-Resources#40
- [ ] As-hina-Gaming/Ampi-lution-Resources#41
- [ ] As-hina-Gaming/Ampi-lution-Resources#42
- [ ] As-hina-Gaming/Ampi-lution-Resources#43
- [ ] As-hina-Gaming/Ampi-lution-Resources#44
- [ ] As-hina-Gaming/Ampi-lution-Resources#1
